If any of the consul agents such as manage, tenant, or warehouse are not set.
This exception is raised:
Exception when host-monitored by console: Object 'NoneType' has no attribute 'get_health': AttributeError: Object 'NoneType' has no attribute 'get_health'.

Now to handle this exception, we just need to check the condition whether the name exists in 'agents.name'.

Change-Id: I00ca3271f52eb4de770dbd719a57b2d15c138833